"""empty message

Revision ID: 202a6d4d4771
Revises: 9ef7d48800d6
Create Date: 2025-09-24 16:10:35.931096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202a6d4d4771'
down_revision = '9ef7d48800d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('mobile_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('mobile_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
